name: Assembly Issue
description: Create a new assembly issue to track
title: "[Issue]: "
labels: ["triage"]
assignees:
  - nhansen
body:
  - type: input
    id: region
    attributes:
      label: Assembly Region
      description: Chromosome, start, and end of problem region
      placeholder: chrX:3000-4000
    validations:
      required: true
  - type: dropdown
    id: assemblyversion
    attributes:
      label: Assembly Version
      description: Which assembly release are these coordinates for?
      options:
        - v0.6
        - v0.7 (Default)
    validations:
      required: true
  - type: dropdown
    id: curator
    attributes:
      label: Who is working on this issue?
      multiple: true
      options:
        - nhansen
        - arangrhie
        - skoren
