---
name: Small error report
description: Report errors in the hg002v1.0 assembly which span just a few bases
about: Use this issue template to describe errors spanning just a small number of bases
  in the v1.0 assembly.
title: Localized issue in the hg002v1.0 assembly
labels: "v1.0"
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to share your observations about the HG002 v1.0 Q100 assembly. Before submitting an issue, please check to be sure it isn't already in our VCF file of issues that are already scheduled to be applied, or our VCF of submitted issues to be evaluated. Both of these VCFs are displayed as tracks in our UCSC browser assembly hub here. 

---
